### PR TITLE
Double IQN

### PR DESCRIPTION
**Pull request by cross32768**
This PR adds Double IQN as in ChainerRL as suggested in #4.
This PR includes new agent `DoubleIQN` and it's training example as well as tests, based on [ChainerRL implementation](https://github.com/chainer/chainerrl/blob/master/chainerrl/agents/double_iqn.py) and [IQN in PFRL](https://github.com/pfnet/pfrl/blob/master/pfrl/agents/iqn.py) .

### CODE REVIEW

**Comment by muupan** [comment]
@cross32768 Sorry for the delayed response! Do you have time/resource for running Atari experiments like https://github.com/chainer/chainerrl/pull/503#issuecomment-515560462 to verify its relative performance to IQN?

**Comment by cross32768** [comment]
I have some computing resource and conducted some experiments to verify correctness of implementation. But to conduct experiment in all Atari environments is difficult for my computing power. Is it okay to verify performance in some parts of Atari environments?

**Comment by muupan** [comment]
Yes, it is fine to run only the subset. It would be perfect if you run the same set of https://github.com/chainer/chainerrl/pull/503#issuecomment-515560462 so that we can compare scores.

**Comment by cross32768** [comment]
I'll add results of experiments on same environments as in [chainer/chainerrl#503 (comment)](https://github.com/chainer/chainerrl/pull/503#issuecomment-515560462) by editing this comment.

All parameter for experiments is default parameter of [training code](https://github.com/cross32768/pfrl/blob/double_iqn/examples/atari/train_double_iqn.py), and reported scores are "mean" of evaluation after 5e7 training steps.

|  Game  |  Double IQN  | IQN |
| :--------: | :--------: | :--------: |
| Asterix | **382320** | 298741 |

**Comment by cross32768** [comment]
I will withdraw the pull request once and try to investigate the cause of problem because all scores observed is lower than PFRL original scores of IQN (https://github.com/pfnet/pfrl/tree/master/examples/atari/reproduction/iqn ).

**Pull request closed without merging**
